version: '3.8'

services:
  # Backend API (using MongoDB Atlas)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mamacare-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      # Using MongoDB Atlas (no local MongoDB needed)
      MONGODB_URI: mongodb+srv://talentmundwa:theresakazingizi@cluster0.fgdy8jz.mongodb.net/mamacare?retryWrites=true&w=majority
      JWT_SECRET: ${JWT_SECRET:-mamacare_super_secret_jwt_key_2025_zimbabwe_healthcare}
      JWT_EXPIRE: 7d
      # CORS for production (update with your domains)
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:3000,http://localhost:5173}
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
      - ./backend/logs:/usr/src/app/logs
    ports:
      - "5000:5000"
    networks:
      - mamacare-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Admin Dashboard (served by nginx)
  admin-dashboard:
    image: nginx:alpine
    container_name: mamacare-admin
    restart: unless-stopped
    volumes:
      - ./admin-dashboard/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - mamacare-network

networks:
  mamacare-network:
    driver: bridge

# Note: No MongoDB volume needed since we're using MongoDB Atlas cloud database
