version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: mamacare-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: mamacare
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
    networks:
      - mamacare-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mamacare-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/mamacare
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE: 7d
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
      - ./backend/logs:/usr/src/app/logs
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - mamacare-network

  # Admin Dashboard (served by nginx)
  admin-dashboard:
    image: nginx:alpine
    container_name: mamacare-admin
    restart: unless-stopped
    volumes:
      - ./admin-dashboard/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - mamacare-network

volumes:
  mongodb_data:

networks:
  mamacare-network:
    driver: bridge
