services:
  - type: web
    name: mamacare-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://talentmundwa:theresakazingizi@cluster0.fgdy8jz.mongodb.net/mamacare?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: CORS_ORIGINS
        value: https://mama-care-g7y1.onrender.com,https://mamacare-admin.onrender.com,https://localhost:3000,http://localhost:3000,https://localhost:5173,http://localhost:5173
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: UPLOAD_PATH
        value: uploads/
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 200
